### PR TITLE
Return empty array as requested by PHPDoc ...

### PR DESCRIPTION
**Pull request by DeepDiver1975**
... followup functions like processICalendarChange expect an array as well. Returning null here will result in a type error

Argument 3 passed to Sabre\\CalDAV\\Schedule\\Plugin::processICalendarChange() must be of the type array, null given

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Is anybody working on the broken tests?

**Comment by staabm** [comment]
I dont think so

**Comment by DeepDiver1975** [comment]
> I dont think so

let me see what I can do these days ...

**Comment by tbille** [comment]
I just made a PR to fix the tests. I am waiting to get some "approvals" to keep the project clean :)
https://github.com/fruux/sabre-dav/pull/965

**Comment by staabm** [comment]
Please rebase

**Comment by staabm** [comment]
Th

**Pull request merged**
