### PR TITLE
Allow asset delivery from within phar files.

### PR DESCRIPTION
**Pull request by tobiastom**
I created a minimal server that provides the Cal|CardDAV functionality for me. I want to deploy it though a single phar file. For me that has the advantage that composer is not needed to be installed and that I can easily update it (to a tested version).

I can see that the check might not be optimal and I'm very open to suggestions to make it better.

### CODE REVIEW

**Comment by staabm** [comment]
I remember that phar based apps are very slow...  did you check that?

Composer itself is not a deployment tool, so it shouldnt be required at all to deploy your source into a production envirnment.

**Comment by tobiastom** [comment]
The answer is of course: it depends. The speed inside the phar file is by far good enough for me. 

When used with an accelerator, I didn't see any difference to plain PHP code.

For me it's just making it work with your code base. Not about recommend it as a go to solution for everyone. ;)

**Comment by staabm** [comment]
I have no opinion on the change itself, but at least we need a test to cover it ;-)

**Comment by evert** [comment]
I don't really want to accept this patch, mainly because I never use `.phar`, nor know anyone that does.  We don't officially support this. This leaves me with a feature I'm not sure if it works, but it is something I need to maintain version over version. No tests doesn't help this.

So since you probably have some custom script to create the .phar build. why don't you just subclass the browser plugin and override that function? That gives you a super clean upgrade path specific to your situation. We don't break that function in minor versions, and if we do in a major version, we really clearly document it. It's how this feature is intended, so please just use that!

**Comment by tobiastom** [comment]
Thank you @evert for your open words. I actually don't know anyone using phar deployment except myself, so you are most likely right. 

I'll go with the sub-class approach.

**Pull request closed without merging**
