### PR TITLE
Fall back to manually seeking if fseek fails.

### PR DESCRIPTION
**Pull request by evert**
This is a potential fix for #787. This targets the 3.0 branch and should
then get merged into the 3.1 and master branches.

@PVince81: How does this look?

### CODE REVIEW

**Comment by evert** [comment]
Travis doesn't like it.

**Comment by evert** [comment]
Corrected the bug. Wanna take a look @PVince81 ?

**Comment by PVince81** [comment]
Thanks a lot! I'll have a look.

**Comment by PVince81** [comment]
Tested the patch against Sabre 3.0, it worked fine. The block of code that eats bytes was correctly triggered. :+1:

**Pull request merged**
