### PR TITLE
SupportedCalendarComponentSet deserializer fails for empty/no values

### PR DESCRIPTION
**Pull request by DominikTo**
* Added SupportedCalendarComponentSetTest

### CODE REVIEW

**Comment by DominikTo** [comment]
`parseInnerTree()` returns `null` here. We could always cast the result from [`$reader->parseInnerTree()`](https://github.com/fruux/sabre-dav/blob/cd4e193e5fbaee33eeaf0e3e6e5945c43e0fa289/lib/CalDAV/Xml/Property/SupportedCalendarComponentSet.php#L110) to an array or only run the loop if `$elems` is an array.

There are two more occurrences that are probably affected by this:

* [`Sabre\CalDAV\Xml\Property\Invite`](https://github.com/fruux/sabre-dav/blob/cd4e193e5fbaee33eeaf0e3e6e5945c43e0fa289/lib/CalDAV/Xml/Property/Invite.php#L193)
* [`Sabre\CalDAV\Xml\Property\ScheduleCalendarTransp`](https://github.com/fruux/sabre-dav/blob/cd4e193e5fbaee33eeaf0e3e6e5945c43e0fa289/lib/CalDAV/Xml/Property/ScheduleCalendarTransp.php#L123)

**Comment by evert** [comment]
One question I would have though... why is it empty? A bug elsewhere?

**Comment by evert** [comment]
The specification actually says that it needs to contain at least 1 sub-component. So I'm changing the test to expect an exception and then fix to code to emit that =)

**Comment by DominikTo** [comment]
:+1:

Does that also apply to `Invite` and `ScheduleCalendarTransp` (see above) that there should never be a case where we run the foreach with a `null` value? At least for `Invite`, we've seen this in fruux/webapp#370.

**Comment by evert** [comment]
Yea true... Just added a new function in sabre/xml to generalize this case. Once sabre/dav updates to sabre/xml 1.2, I can just mass-replace `parseInnerTree` with `parseGetElements`.

https://github.com/fruux/sabre-xml/issues/39

**Pull request merged**
