### PR TITLE
`s/httpPropPatch/httpProppatch`

### PR DESCRIPTION
**Pull request by Hywan**
The method did not have the correct case.

I assign @evert for the merge (don't know if we should merge on `master`, I guess it would).

### CODE REVIEW

**Comment by DominikTo** [comment]
Maybe we should change it in https://github.com/Hywan/sabre-dav/blob/httpproppatch/lib/DAV/CorePlugin.php#L41 instead. In other places `propPatch` seems to be used. Apparently also for events that are fired etc.

**Comment by evert** [comment]
Hmm.. yea I've been using casing such as propFind, propPatch, mkCol. Are we calling it `httpProppatch` somewhere?

**Comment by Hywan** [comment]
So I should rename `httpPropfind` to `httpPropFind` too. Will do that after some sleep ;-).

**Comment by Hywan** [comment]
Done.

**Comment by evert** [comment]
thank you =)

**Pull request merged**
