### PR TITLE
Returning 418 I'm a Teapot in multistatus with no properties.

### PR DESCRIPTION
**Pull request by evert**
This one is for @DeepDiver1975 & @helje5

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
With this patch applied CalDAVTester suceeds - THX :+1:

**Comment by DeepDiver1975** [comment]
@evert we need this on 3.0 as well :wink: THX

**Comment by evert** [comment]
Merged to 3.0

**Comment by DeepDiver1975** [comment]
THX a lot!

**Comment by DeepDiver1975** [comment]
> With this patch applied CalDAVTester suceeds - THX :+1:

hmmm .... we are back now on CalDAVTester to NOT accept 418 as valid status - see https://travis-ci.org/owncloud/core/jobs/93900387#L377

Time to adopt CalDAVTester?

**Comment by DeepDiver1975** [comment]
Brilliant - I fooled myself - https://travis-ci.org/owncloud/core/jobs/93916323

**Pull request merged**
