### PR TITLE
Added support for PSR-3.

### LINKED ISSUE #397: Graceful Exception Handling with optional logging
If you are silly like me and forget to run the 'migrate' scripts then you have missing columns hence you get 500 and 565 HTTP errors back, which is all there is to see in the logs.

To determine what the heck was going on I instrumented the Server Exception handler with (not a patch, just a quick hack to be able to see what goes wrong):

```
--- a/lib/Sabre/DAV/Server.php
+++ b/lib/Sabre/DAV/Server.php
@@ -305,6 +305,8 @@ class Server extends EventEmitter {
             }
             $headers['Content-Type'] = 'application/xml; charset=utf-8';

+if (floor($httpCode / 100) == 5) error_log("EXCEPTION: ".print_r($e, true));
+
             $this->httpResponse->setStatus($httpCode);
             $this->httpResponse->addHeaders($headers);
             $this->httpResponse->setBody($DOM->saveXML());
```

This produced in my error log the useful:
```
[08-Jan-2014 13:07:49 UTC] EXCEPTION: PDOException Object
(
    [message:protected] => SQLSTATE[HY000]: General error: 1 no such column: synctoken
    [string:Exception:private] =>
    [code:protected] => HY000
    [file:protected] => ../sabre-dav/lib/Sabre/CalDAV/Backend/PDO.php
    [line:protected] => 151
...
```

and then I knew what the problem was ;)

It would be great if these exceptions, and a possible hint "hey, silly, you did not run the migrate yet" could be logged somewhere. error_log() is a great way; though indeed that might mix with the output if the config did not set a output file, hence a check for that would be a good thing.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/6407974-graceful-exception-handling-with-optional-logging?utm_campaign=plugin&utm_content=tracker%2F294006&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F294006&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by evert**
Fixes #397.

Ready for review

### CODE REVIEW

**Comment by kriswebdev** [comment]
This led to `Fatal error: Interface 'Psr\Log\LoggerAwareInterface' not found in /.../sabredav/vendor/sabre/dav/lib/DAV/Server.php on line 23` using the last master branch.

Is it a bug or is it a dependency?  (i.e. is PSR-3 an option or a requirement)

Are there install instructions to use the master branch instead of the release package? I've just put the git repo in place of `sabredav/vendor/sabre/dav`). I'd like to experiment share calendar support.

Guess I'll have to install PSR-3 in the meantime.

**Comment by staabm** [comment]
@kriswebdev did you run `composer install`? This PR added a new dependency..

**Comment by staabm** [comment]
Docs for install will be added via https://github.com/fruux/sabre-dav/pull/824

**Comment by evert** [comment]
@kriswebdev you really need to take the 10 minutes to learn composer. It's an essential skill if you do anything with PHP. Its a terrible idea to manually mess with dependencies

**Comment by kriswebdev** [comment]
Thanks, I'll do that.

**Comment by benrubson** [comment]
I was not able to figure out how to make `$this->server->getLogger()->log()` log into webserver log, as `error_log()` would do...
And did not found anything relevant into the documentation.
Did I miss something ?
Thank you 👍

**Comment by evert** [comment]
By default the `NullLogger` is used, which basically discards every log message. To get real logs, you need to set a logger using `setLogger()`. A great package for this is the Monolog composer package. It has a TON of options

**Pull request merged**
