### PR TITLE
add button to export an addressbook in the browser

### PR DESCRIPTION
**Pull request by mgee**

### CODE REVIEW

**Comment by evert** [comment]
The broken unittest here is related to #668, not to this change.

**Comment by evert** [comment]
Messed up the issue numbers :/ I think this is fine to merge otherwise @Hywan , not that concerned about a unittest for this thing.

**Comment by mgee** [comment]
@evert thanks for merging, sorry didn't notice the unittest...

**Comment by staabm** [comment]
looks good

**Pull request merged**
