### PR TITLE
Enable php7 on travis

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@evert here we go - php7 for sabre-dav 2.1

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Whats wrong with travis on this one?

**Comment by staabm** [comment]
@DeepDiver1975 you might use https://github.com/etsy/phan to check the project for php7 Bc issues

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 you might use https://github.com/etsy/phan to check the project for php7 Bc issues

THX for the hint - but tests are already passing locally with php 7.0.1

**Comment by staabm** [comment]
Hmm the PR doesnt even show up on https://travis-ci.org/fruux/sabre-dav/pull_requests

Looks like a travis issue. Maybe @svenfuchs can give us a hint.

**Comment by DeepDiver1975** [comment]
rebase with upstream did the trick :tada:

**Comment by staabm** [comment]
Looks like some of the dependencies do not support 7.x yet, see travis loh output

**Comment by DeepDiver1975** [comment]
> Looks like some of the dependencies do not support 7.x yet, see travis loh output

bääääh .... will have a look on Monday

**Comment by evert** [comment]
It's actually just composer.json for the main sabre/dav package that specifies PHP < 7

**Comment by evert** [comment]
Oddly enough the diff no longer contains the PHP 7 changes. I think your conflict resolution may have removed it?

**Comment by DeepDiver1975** [comment]
@evert GREEN!

**Comment by DeepDiver1975** [comment]
THX!

**Pull request merged**
